### ISSUE TITLE
Huobi timstamp varies for identical message across different sockets.

### ISSUE THREAD

**Issue by lostless13** [altangent/ccxws#135]
**Exchange**
Huobi

**Subscription type**
Level2 orderbook updates

**Describe the bug**
If you subscribe to L2 updates for the same market on different websockets the timestamp will vary for the same message.

**To Reproduce**
1. Open two or more websockets and subscribe to L2 updates on a market
2. Monitor timestamps of messages between markets
3. Identical messages will have different timestamps.

**Additional context**
Recommendation is to switch to the using the tick.version on the update from Huobi. I overrode this method and tested. It appears to be unique across websockets.

**Comment by bmancini55** [comment]
Thanks for submitting the issue!

I took a look at two raw streams, there are definitely different `ts` values for what is essentially the same data. 

As you suggested, `tick.version` is repeatable across streams.  This looks like an increasing identifier which we can use for the `sequenceId` values of `Level2Snapshot`.  

It also has `tick.ts` value which is consistent across stream.  This should be used for `timestampMs` instead of the root `ts`, which is likely the timestamp of the message instead of the underlying data.


### Socket 1
```
{
  "ch": "market.ethbtc.depth.step0",
  "ts": 1583253938053,
  "tick": {
    "bids": [
      [
        0.025441,
        9.4629
      ],
      [
        0.02544,
        6.8751
      ],
      [
        0.025439,
        0.1135
      ]
    ],
    "asks": [
      [
        0.025445,
        3.6
      ],
      [
        0.025447,
        1.8566
      ],
      [
        0.025449,
        19.5
      ],
    ],
    "version": 101973723128,
    "ts": 1583253938008
  }
}
```

### Socket 2
```
{
  "ch": "market.ethbtc.depth.step0",
  "ts": 1583253938058,
  "tick": {
    "bids": [
      [
        0.025441,
        9.4629
      ],
      [
        0.02544,
        6.8751
      ],
      [
        0.025439,
        0.1135
      ]      
    ],
    "asks": [
      [
        0.025445,
        3.6
      ],
      [
        0.025447,
        1.8566
      ],
      [
        0.025449,
        19.5
      ]
    ],
    "version": 101973723128,
    "ts": 1583253938008
  }
}

```

I'm happy to make these 2 changes, but probably won't get to it today.  If you're interested in submitting a PR, just let know!
