### ISSUE TITLE
Orderbook Grouping for Bitmex

### ISSUE THREAD

**Issue by pavs94** [altangent/ccxws#159]
Hello, 

There are exchange like bitmex that offer orderbook grouping features by price - 0.5, 1, 5, 10 and so on. Is it possible to add this feature to this library?

**Comment by bmancini55** [comment]
Hi, sorry for the delay, this slipped through the cracks!   I'm not exactly sure what feature you are asking, do you have an example you can send along?

For some color, right now CCXWS is only relaying order book information provided by the exchange which can be in two formats: 
* snapshot - a fully constructed order book up to a depth provided by the exchange (usually a depth of 25 or 100 price levels).  
* updates streams - provides a stream of updated price levels since the last update

This library does not currently have the capability to construct or maintain the book from an update stream which would be needed to create snapshots.  It's something we would like to add, but haven't gotten there yet.
