### ISSUE TITLE
ccxt market id

### ISSUE THREAD

**Issue by ais-one** [altangent/ccxws#89]
**Exchange**
ALL

**Subscription type**
AlLL

**Describe the bug**
ccxt uses [BASE]/[QUOTE] for pair symbols / id, are we able to follow as well?

for Bibox currently, one needs to pass in [BASE]_[QUOTE] to work...

internally, there should be a function to convert from ccxt symbol / id, to the one used by the exchange.

I can do it for bibox and make change if you wish, every public facing function on the exchange with market as input parameter will need to have the conversion if the format is not [BASE]/[QUOTE]

**To Reproduce**
use ETH/BTC as market id

**Expected behavior**
There will be error similar to "channel not valid" in chinese

**Additional context**
N.A.

**Comment by bmancini55** [comment]
Hi, thanks for submitting an issue.  

It looks like you are using an incorrect `id` for your market.  CCXWS markets use the results of a call to CCXT `fetchMarket`.  These results have an `id` property that is the remote exchange's identifier.  CCXT does the work of normalizing the base and quote symbols across all exchanges.

Kraken is a good example.  On that exchange, Bitcoin is XXBT and the BTC/USD market looks like:
```
{
    id: 'XXBTZUSD',  
    symbol: 'BTC/USD',
    base: 'BTC',
    quote: 'USD',
    baseId: 'XXBT',
    quoteId: 'ZUSD',
}
```
- `id` is the remote identifier the exchange is expected
- `base` is the normalized base symbol
- `quote` is the normalized quote symbol
- `symbol` is the concatenation of normalized base and quote symbols
- `baseId` is the base symbol used by the exchange
- `quoteId` is the quote symbol used by the exchange

It's not obvious that this is the case with Bibox because most markets are already using a symbol that is normalized.

For example, BTC/USDT on Bibox looks like

```
{
    id: 'BTC_USDT',
    symbol: 'BTC/USDT',
    base: 'BTC',
    quote: 'USDT',
    baseId: 'BTC',
    quoteId: 'USDT',
}
```

Hopefully that answers you question.

**Comment by ais-one** [comment]
I see, I usually pass in the symbol when calling the ccxt APIs. Will close this and handle accordingly...
